### ISSUE TITLE
Select outgoing network interface

### ISSUE THREAD

**Issue by johannrichard** [diladele/dnssafety#197]
It would be great if the outgoing network interface(s) for the forwarder could be defined/selected (see pfSense UI example, also as inspiration for the pfSense UI):

<img width="707" alt="Outgoing Network Interfaces" src="https://user-images.githubusercontent.com/189003/54153787-b82c0880-4440-11e9-9852-8d804ec75169.png">

**Comment by ra-at-diladele-com** [comment]
One per forwarder or one setting applicable for all forwarders?

**Comment by johannrichard** [comment]
One for all forwarders is probably the right choice, provided that forward requests are made in a `round robin` manner (e.g. all forwarders are treated as equal).
