### ISSUE TITLE
Help with regular expressions

### ISSUE THREAD

**Issue by marcosvsmorais** [diladele/dnssafety#275]
I'm trying to use a regular expression but it's not working. Could you give me an example?
I want to block all urls that have the word "isimples"
For example:
isimples.com.br
novo.isimples.com
ipam.isimples.com.br
www.isimples.com.br

Thanks for your attention! :)

**Comment by ra-at-diladele-com** [comment]
Hello Marcos, I will take a look today and get back to you.

**Comment by marcosvsmorais** [comment]
Thanks for your attention! This help me so much :)
The dnssafety is a great project

**Comment by ra-at-diladele-com** [comment]
There was  a bug both in block domain name by regex and exclude by regex. I have fixed it, will be published when 0.8 is available (two weeks approx). Leaving the issue as open in testing milestone.

**Comment by ra-at-diladele-com** [comment]
The regex is btw `(.*\.)?isimples\..*`

**Comment by marcosvsmorais** [comment]
Thansk for your attention!
I will wait for the update 0.8 to use this feature :)

**Comment by ra-at-diladele-com** [comment]
Ok 0.8 is out, closing.
