### ISSUE TITLE
Integrate IWF and CTIRU block lists

### ISSUE THREAD

**Issue by danieljloughlin** [diladele/dnssafety#443]
Not sure if this is feasible, but integrating the Internet Watch Foundation (IWF) and Counter Terrorism Internet Referral Unit (CTIRU) block lists, as used by Web Safety, would be extremely useful.

**Comment by ra-at-diladele-com** [comment]
IWF explicitly prohibit the use of their lists in DNS filtering. CTIRU has URLS not domain names. Closing as wont fix.
